apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    tier: front-end
spec: 
  template: 
    metadata:
     name: myapp-pod
     labels:
       app: myapp
       tier: front-end
    spec:
     containers:
      - name: myapp
        image: nginx
        env: 
         -  name: POSTGRES_PASSWORD
            value: mysecretpassword
  replicas: 3