apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
    tier: front-end-service
spec: 
  type: ClusterIP
  ports: 
   - targetPort: 80
     port: 80
  selector: 
    app: myapp
    type: front-end